// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"UserService/repo"
	"UserService/service"
	"context"
	"github.com/google/wire"
	"log"
	"os"
)

// Injectors from wire.go:

func InitializeUserRepo(ctx context.Context) (repo.UserRepo, error) {
	logger := ProvideRepoLogger()
	db := repo.ProvideConnection()
	userRepo := repo.ProvideUserRepo(logger, db)
	return userRepo, nil
}

func InitializeUserService() service.UserService {
	logger := ProvideRepoLogger()
	db := repo.ProvideConnection()
	userRepo := repo.ProvideUserRepo(logger, db)
	serviceLogger := ProvideServiceLogger()
	userService := service.ProvideUserService(userRepo, serviceLogger)
	return userService
}

// wire.go:

var repoSet = wire.NewSet(ProvideRepoLogger, repo.ProvideConnection, repo.ProvideUserRepo)

func ProvideServiceLogger() *service.ServiceLogger {
	return (*service.ServiceLogger)(log.New(os.Stdout, "USER_SERVICE", 1))
}

func ProvideRepoLogger() *log.Logger {
	return log.New(os.Stdout, "USER_REPO", 1)
}
