// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"UserService/repo"
	"UserService/service"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeUserRepo(ctx context.Context) (repo.UserRepo, error) {
	db := repo.ProvideConnection()
	userRepo := repo.ProvideUserRepo(db)
	return userRepo, nil
}

func InitializeRoleRepo(ctx context.Context) (repo.RoleRepo, error) {
	db := repo.ProvideConnection()
	roleRepo := repo.ProvideRoleRepo(db)
	return roleRepo, nil
}

func InitializeUserService() service.UserService {
	db := repo.ProvideConnection()
	userRepo := repo.ProvideUserRepo(db)
	roleRepo := repo.ProvideRoleRepo(db)
	userService := service.ProvideUserService(userRepo, roleRepo)
	return userService
}

func InitializeAuthService() service.AuthService {
	db := repo.ProvideConnection()
	userRepo := repo.ProvideUserRepo(db)
	roleRepo := repo.ProvideRoleRepo(db)
	authService := service.ProvideAuthService(userRepo, roleRepo)
	return authService
}

// wire.go:

var userRepoSet = wire.NewSet(repo.ProvideConnection, repo.ProvideUserRepo)

var roleRepoSet = wire.NewSet(repo.ProvideConnection, repo.ProvideRoleRepo)
