// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"RepoService/repo"
	"RepoService/service"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeSourceRepo(ctx context.Context) (repo.SourceRepo, error) {
	db := repo.ProvideConnection()
	sourceRepo := repo.ProvideSourceRepo(db)
	return sourceRepo, nil
}

func InitializeSourceService() service.SourceService {
	db := repo.ProvideConnection()
	sourceRepo := repo.ProvideSourceRepo(db)
	collabRepo := repo.ProvideCollabRepo(db)
	sourceService := service.ProvideSourceService(sourceRepo, collabRepo)
	return sourceService
}

func InitializeCollabRepo(ctx context.Context) (repo.CollabRepo, error) {
	db := repo.ProvideConnection()
	collabRepo := repo.ProvideCollabRepo(db)
	return collabRepo, nil
}

func InitializeCollabService() service.CollabService {
	db := repo.ProvideConnection()
	collabRepo := repo.ProvideCollabRepo(db)
	collabService := service.ProvideCollabService(collabRepo)
	return collabService
}

// wire.go:

var userRepoSet = wire.NewSet(repo.ProvideConnection, repo.ProvideSourceRepo)

var collabRepoSet = wire.NewSet(repo.ProvideConnection, repo.ProvideCollabRepo)
