// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"RepoService/repo"
	"RepoService/service"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeSourceRepo(ctx context.Context) (repo.SourceRepo, error) {
	db := repo.ProvideConnection()
	sourceRepo := repo.ProvideSourceRepo(db)
	return sourceRepo, nil
}

func InitializeSourceService() service.SourceService {
	db := repo.ProvideConnection()
	sourceRepo := repo.ProvideSourceRepo(db)
	sourceService := service.ProvideSourceService(sourceRepo)
	return sourceService
}

// wire.go:

var userRepoSet = wire.NewSet(repo.ProvideConnection, repo.ProvideSourceRepo)
