version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=sourceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local