version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    command: mongod --port 27018
    environment:
      - MONGO_INITDB_DATABASE=tease_stats
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27018:27018'
    volumes: 
      - mongodb:/var/lib/mongo/data

volumes:
  mongodb:
    driver: local